### ISSUE TITLE
Are the example compatible with hosting on Vercel using "Serverless" mode?

### ISSUE THREAD

**Issue by Vadorequest** [flawyte/vercel-basic-auth#11]
It's unclear to me if any of the examples there are compatible with the Next.js "serverless" mode, hosted on Vercel.

**Comment by flawyte** [comment]
As I said on the other issue you opened (flawyte/static-auth#3), the `static-auth` package, but also all the examples in this repo, only show how to add basic auth to **static** pages.

If you want to add basic auth to SSR or API routes, you'll have to do it manually or use a package specifically designed for the framework you're using, like [nextjs-basic-auth-middleware](https://www.npmjs.com/package/nextjs-basic-auth-middleware) if your project uses Next.js (disclaimer: I haven't tried this package).
