### ISSUE TITLE
How to get it working

### ISSUE THREAD

**Issue by RickCogley** [flawyte/vercel-basic-auth#18]
Hi - thank you for putting this together. I've been trying to figure out how to password protect a standard static HTML site on Vercel. It looks like I can use one of these as a wrapper. 

In testing these examples, should I just run `vercel` from a local copy of the repo, and specify the "root directory" as `node` or the other two, correct? Or is it better to use `./`?

**Comment by flawyte** [comment]
Hi,

If I understand correctly, you want to run the examples locally to test them, right? The [root package.json](https://github.com/flawyte/vercel-basic-auth/blob/master/package.json) file already contains NPM scripts to do exactly this. After running `npm install` from the root directory, just type `npm run` followed by the name of the example you want to run, for example `npm run node-static-auth` to run the `node-static-auth` example. These scripts will run `vercel dev` under the hood for you. Then just follow whatever steps the Vercel CLI will take you through.

I haven't worked on this project nor used Vercel in a while though, so I don't know if this still works with the latest Vercel CLI version. Let me know if you run into any problem.

**Comment by RickCogley** [comment]
Thanks for taking the time. Well noted!
