### ISSUE TITLE
Simple basic auth for SPA's using `vercel.json`

### ISSUE THREAD

**Issue by ubergarm** [flawyte/vercel-basic-auth#24]
It seems like you might be able to add basic auth to a simple SPA using `vercel.json` like so:

https://github.com/orgs/vercel/discussions/2920

**Comment by flawyte** [comment]
Hey! Thanks for the tip!
Would you mind submitting a PR in new `vercel-json` example directory?

**Comment by ubergarm** [comment]
Yeah, the only reason for SPA is the first bit `"src": "/[^.]+",` stuff to send everything to `/`. You can add basic auth in general to anything with just something like this block as `vercel.json`

```json
{
  "routes": [
    {
      "src": "/.*",
      "dest": "/401",
      "status": 401,
      "headers": { "www-authenticate": "Basic realm=\"secure\"" },
      "missing": [
        {
          "type": "header",
          "key": "authorization",
          "value": "Basic YWxhZGRpbjpvcGVuc2VzYW1l"
        }
      ]
    }
  ]
}
```

Sure I'll see about putting this in a PR for the examples.
